### ISSUE TITLE
Demander à Bordeaux Métropole de libérer ses XML

### ISSUE THREAD

**Issue by DavidBruant** [dtc-innovation/finances-publiques-france#8]
https://www.bordeaux-metropole.fr/content/download/21138/file_pdf/P0AJM.pdf

Demande faite [par email](https://www.bordeaux-metropole.fr/Metropole/Bordeaux-Metropole-a-votre-service/Acces-aux-documents-administratifs) le samedi 6 avril 2019

Pas encore d'accusé de réception

**Comment by DavidBruant** [comment]
Beaucoup de données 
https://data.bordeaux-metropole.fr/data.php?layer=1269&themes=13
"Documents budgétaires PES"

**Comment by thom4parisot** [comment]
@DavidBruant question : est-ce que c'est possible de recopier le contenu de l'email ici ? J'aimerais m'en inspirer ; et voir comment je formule une demande similaire mais pour une commune qui ne dispose pas d'un portail open data, et que j'imagine moins sensible à la démarche de mise à disposition d'un tel document.

**Comment by DavidBruant** [comment]
Ça s'est passé de manière un peu bizarre. J'ai envoyé un premier email qui n'a pas été compris, puis j'ai envoyé une autre demande en réponse. Je te file les deux.

L'email initial : 

> Bonjour,
> 
> Dans le cadre du contrôle des documents budgétaires, vous envoyez de manière dématérialisée à la Préfecture de la Gironde des fichiers XML (sûrement produits avec l’application TotEM). Ces fichiers contiennent les données relatives aux documents budgétaires suivants : comptes administratifs, budgets primitifs, budgets supplémentaires et décisions modificatives
> 
> Je vous prie de bien vouloir publier en ligne ces fichiers pour toutes les années pour lesquels ils ont été produits
>
> Certains de ces documents contiennent des noms de personnes physiques, que vous devrez occulter dans la mesure où leur divulgation porterait atteinte à la protection de la vie privée. Un outil libre vous permet d’ores et déjà de procéder à ce traitement d’usage courant : https://dtc-innovation.github.io/anonymisation-document-budgetaire/
>
> Je me tiens à votre disposition pour toute question que vous auriez suite à ma demande
Je me tiens aussi à votre disposition, à titre bénévole, pour toute aide que je pourrais apporter à vos services quant à la concrétisation de cette demande
>
> En vous remerciant par avance,
>
> David Bruant

La deuxième demande (morceau de l'email) : 

> Je me permets de formuler dans cet email une autre demande en précisant que ma demande concerne spécifiquement Bordeaux Métropole
J'ai déjà eu accès à de tels fichiers pour une autre collectivité et j'ai documenté une manière de trouver ces fichiers au sein d'une collectivité dans le document suivant : https://github.com/DavidBruant/colors-of-the-finances/blob/master/docs/ou-trouver.md#o%C3%B9comment-trouver-les-fichiers-documentbudgetaire
Ce document vous sera peut-être utile afin de localiser le-dit document
Chez les Métropoles spécifiquement, il y a une obligation de produire ces documents, donc je suppose qu'ils existent : https://www.banquedesterritoires.fr/la-teletransmission-des-documents-budgetaires-va-devenir-obligatoire-pour-les-plus-grandes

---

L'email initial est volontairement plutôt "doux" et moins formel/légal parce qu'ils ont mis en place un service dédié, donc ils sont plutôt de bonne volonté ; pas envie de se la jouer cowboy-légaliste-procédurier

Un modèle proche est aussi disponible ici : https://github.com/dtc-innovation/finances-publiques-france/blob/master/op%C3%A9ration%20Gironde/mod%C3%A8les/email%20dada%20l%C3%A9gal%20mais%20gentil.md

**Comment by thom4parisot** [comment]
Super, merci 🙂
